// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'FirebaseOptions.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaSUmYiKdzUhJQtwUFAhFjgshESnlTOhM',
    appId: '1:358514885038:web:4784ab57a8a855ce61083f',
    messagingSenderId: '358514885038',
    projectId: 'yabnet-8ccac',
    authDomain: 'yabnet-8ccac.firebaseapp.com',
    databaseURL: 'https://yabnet-8ccac-default-rtdb.firebaseio.com',
    storageBucket: 'yabnet-8ccac.appspot.com',
    measurementId: 'G-Z0GS4LRTZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5phgEEsCuWRkJxCKnCdBV2AMh0hnKBk',
    appId: '1:358514885038:android:1edaac72e8745efa61083f',
    messagingSenderId: '358514885038',
    projectId: 'yabnet-8ccac',
    databaseURL: 'https://yabnet-8ccac-default-rtdb.firebaseio.com',
    storageBucket: 'yabnet-8ccac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqoneAqHkIN25wyaFTlxPuUOWRdOONnpc',
    appId: '1:358514885038:ios:0901b59837bdcf2b61083f',
    messagingSenderId: '358514885038',
    projectId: 'yabnet-8ccac',
    databaseURL: 'https://yabnet-8ccac-default-rtdb.firebaseio.com',
    storageBucket: 'yabnet-8ccac.appspot.com',
    iosBundleId: 'com.app.yabnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqoneAqHkIN25wyaFTlxPuUOWRdOONnpc',
    appId: '1:358514885038:ios:c88a6c0f08c51c4761083f',
    messagingSenderId: '358514885038',
    projectId: 'yabnet-8ccac',
    databaseURL: 'https://yabnet-8ccac-default-rtdb.firebaseio.com',
    storageBucket: 'yabnet-8ccac.appspot.com',
    iosBundleId: 'com.example.yabnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaSUmYiKdzUhJQtwUFAhFjgshESnlTOhM',
    appId: '1:358514885038:web:d5f5c2e5f757b15561083f',
    messagingSenderId: '358514885038',
    projectId: 'yabnet-8ccac',
    authDomain: 'yabnet-8ccac.firebaseapp.com',
    databaseURL: 'https://yabnet-8ccac-default-rtdb.firebaseio.com',
    storageBucket: 'yabnet-8ccac.appspot.com',
    measurementId: 'G-60TFZRZPCM',
  );
}
