import '../../data/CountryData.dart';

class CountryCollection {
  static List<CountryData> getCountryList() {
    List<CountryData> rawData = [
      CountryData(
        isoCode: "AF",
        phoneCode: "93",
        name: "Afghanistan",
        iso3Code: "AFG",
      ),
      CountryData(
        isoCode: "AL",
        phoneCode: "355",
        name: "Albania",
        iso3Code: "ALB",
      ),
      CountryData(
        isoCode: "DZ",
        phoneCode: "213",
        name: "Algeria",
        iso3Code: "DZA",
      ),
      CountryData(
        isoCode: "AS",
        phoneCode: "1",
        name: "American Samoa",
        iso3Code: "ASM",
      ),
      CountryData(
        isoCode: "AD",
        phoneCode: "376",
        name: "Andorra",
        iso3Code: "AND",
      ),
      CountryData(
        isoCode: "AO",
        phoneCode: "244",
        name: "Angola",
        iso3Code: "AGO",
      ),
      CountryData(
        isoCode: "AI",
        phoneCode: "1",
        name: "Anguilla",
        iso3Code: "AIA",
      ),
      CountryData(
        isoCode: "AQ",
        phoneCode: "672",
        name: "Antarctica",
        iso3Code: "ATA",
      ),
      CountryData(
        isoCode: "AG",
        phoneCode: "1",
        name: "Antigua and Barbuda",
        iso3Code: "ATG",
      ),
      CountryData(
        isoCode: "AR",
        phoneCode: "54",
        name: "Argentina",
        iso3Code: "ARG",
      ),
      CountryData(
        isoCode: "AM",
        phoneCode: "374",
        name: "Armenia",
        iso3Code: "ARM",
      ),
      CountryData(
        isoCode: "AW",
        phoneCode: "297",
        name: "Aruba",
        iso3Code: "ABW",
      ),
      CountryData(
        isoCode: "AU",
        phoneCode: "61",
        name: "Australia",
        iso3Code: "AUS",
      ),
      CountryData(
        isoCode: "AT",
        phoneCode: "43",
        name: "Austria",
        iso3Code: "AUT",
      ),
      CountryData(
        isoCode: "AZ",
        phoneCode: "994",
        name: "Azerbaijan",
        iso3Code: "AZE",
      ),
      CountryData(
        isoCode: "BS",
        phoneCode: "1",
        name: "Bahamas",
        iso3Code: "BHS",
      ),
      CountryData(
        isoCode: "BH",
        phoneCode: "973",
        name: "Bahrain",
        iso3Code: "BHR",
      ),
      CountryData(
        isoCode: "BD",
        phoneCode: "880",
        name: "Bangladesh",
        iso3Code: "BGD",
      ),
      CountryData(
        isoCode: "BB",
        phoneCode: "1",
        name: "Barbados",
        iso3Code: "BRB",
      ),
      CountryData(
        isoCode: "BY",
        phoneCode: "375",
        name: "Belarus",
        iso3Code: "BLR",
      ),
      CountryData(
        isoCode: "BE",
        phoneCode: "32",
        name: "Belgium",
        iso3Code: "BEL",
      ),
      CountryData(
        isoCode: "BZ",
        phoneCode: "501",
        name: "Belize",
        iso3Code: "BLZ",
      ),
      CountryData(
        isoCode: "BJ",
        phoneCode: "229",
        name: "Benin",
        iso3Code: "BEN",
      ),
      CountryData(
        isoCode: "BM",
        phoneCode: "1",
        name: "Bermuda",
        iso3Code: "BMU",
      ),
      CountryData(
        isoCode: "BT",
        phoneCode: "975",
        name: "Bhutan",
        iso3Code: "BTN",
      ),
      CountryData(
        isoCode: "BO",
        phoneCode: "591",
        name: "Bolivia, Plurinational State of",
        iso3Code: "BOL",
      ),
      CountryData(
        isoCode: "BA",
        phoneCode: "387",
        name: "Bosnia and Herzegovina",
        iso3Code: "BIH",
      ),
      CountryData(
        isoCode: "BW",
        phoneCode: "267",
        name: "Botswana",
        iso3Code: "BWA",
      ),
      CountryData(
        isoCode: "BV",
        phoneCode: "47",
        name: "Bouvet Island",
        iso3Code: "BVT",
      ),
      CountryData(
        isoCode: "BR",
        phoneCode: "55",
        name: "Brazil",
        iso3Code: "BRA",
      ),
      CountryData(
        isoCode: "IO",
        phoneCode: "246",
        name: "British Indian Ocean Territory",
        iso3Code: "IOT",
      ),
      CountryData(
        isoCode: "BN",
        phoneCode: "673",
        name: "Brunei Darussalam",
        iso3Code: "BRN",
      ),
      CountryData(
        isoCode: "BG",
        phoneCode: "359",
        name: "Bulgaria",
        iso3Code: "BGR",
      ),
      CountryData(
        isoCode: "BF",
        phoneCode: "226",
        name: "Burkina Faso",
        iso3Code: "BFA",
      ),
      CountryData(
        isoCode: "BI",
        phoneCode: "257",
        name: "Burundi",
        iso3Code: "BDI",
      ),
      CountryData(
        isoCode: "KH",
        phoneCode: "855",
        name: "Cambodia",
        iso3Code: "KHM",
      ),
      CountryData(
        isoCode: "CM",
        phoneCode: "237",
        name: "Cameroon",
        iso3Code: "CMR",
      ),
      CountryData(
        isoCode: "CA",
        phoneCode: "1",
        name: "Canada",
        iso3Code: "CAN",
      ),
      CountryData(
        isoCode: "CV",
        phoneCode: "238",
        name: "Cape Verde",
        iso3Code: "CPV",
      ),
      CountryData(
        isoCode: "BQ",
        phoneCode: "599",
        name: "Caribbean Netherlands",
        iso3Code: "BES",
      ),
      CountryData(
        isoCode: "KY",
        phoneCode: "1",
        name: "Cayman Islands",
        iso3Code: "CYM",
      ),
      CountryData(
        isoCode: "CF",
        phoneCode: "236",
        name: "Central African Republic",
        iso3Code: "CAF",
      ),
      CountryData(
        isoCode: "TD",
        phoneCode: "235",
        name: "Chad",
        iso3Code: "TCD",
      ),
      CountryData(
        isoCode: "CL",
        phoneCode: "56",
        name: "Chile",
        iso3Code: "CHL",
      ),
      CountryData(
        isoCode: "CN",
        phoneCode: "86",
        name: "China",
        iso3Code: "CHN",
      ),
      CountryData(
        isoCode: "CX",
        phoneCode: "61",
        name: "Christmas Island",
        iso3Code: "CXR",
      ),
      CountryData(
        isoCode: "CC",
        phoneCode: "61",
        name: "Cocos (Keeling) Islands",
        iso3Code: "CCK",
      ),
      CountryData(
        isoCode: "CO",
        phoneCode: "57",
        name: "Colombia",
        iso3Code: "COL",
      ),
      CountryData(
        isoCode: "KM",
        phoneCode: "269",
        name: "Comoros",
        iso3Code: "COM",
      ),
      CountryData(
        isoCode: "CG",
        phoneCode: "242",
        name: "Congo",
        iso3Code: "COG",
      ),
      CountryData(
        isoCode: "CD",
        phoneCode: "243",
        name: "Congo",
        iso3Code: "COD",
      ),
      CountryData(
        isoCode: "CK",
        phoneCode: "682",
        name: "Cook Islands",
        iso3Code: "COK",
      ),
      CountryData(
        isoCode: "CR",
        phoneCode: "506",
        name: "Costa Rica",
        iso3Code: "CRI",
      ),
      CountryData(
        isoCode: "HR",
        phoneCode: "385",
        name: "Croatia",
        iso3Code: "HRV",
      ),
      CountryData(
        isoCode: "CU",
        phoneCode: "53",
        name: "Cuba",
        iso3Code: "CUB",
      ),
      CountryData(
        isoCode: "CW",
        phoneCode: "599",
        name: "Curaçao",
        iso3Code: "CUW",
      ),
      CountryData(
        isoCode: "CY",
        phoneCode: "357",
        name: "Cyprus",
        iso3Code: "CYP",
      ),
      CountryData(
        isoCode: "CZ",
        phoneCode: "420",
        name: "Czech Republic",
        iso3Code: "CZE",
      ),
      CountryData(
        isoCode: "CI",
        phoneCode: "225",
        name: "Côte d'Ivoire",
        iso3Code: "CIV",
      ),
      CountryData(
        isoCode: "DK",
        phoneCode: "45",
        name: "Denmark",
        iso3Code: "DNK",
      ),
      CountryData(
        isoCode: "DJ",
        phoneCode: "253",
        name: "Djibouti",
        iso3Code: "DJI",
      ),
      CountryData(
        isoCode: "DM",
        phoneCode: "1767",
        name: "Dominica",
        iso3Code: "DMA",
      ),
      CountryData(
        isoCode: "DO",
        phoneCode: "1",
        name: "Dominican Republic",
        iso3Code: "DOM",
      ),
      CountryData(
        isoCode: "EC",
        phoneCode: "593",
        name: "Ecuador",
        iso3Code: "ECU",
      ),
      CountryData(
        isoCode: "EG",
        phoneCode: "20",
        name: "Egypt",
        iso3Code: "EGY",
      ),
      CountryData(
        isoCode: "SV",
        phoneCode: "503",
        name: "El Salvador",
        iso3Code: "SLV",
      ),
      CountryData(
        isoCode: "GB-ENG",
        phoneCode: "44",
        name: "England",
        iso3Code: "GBR",
      ),
      CountryData(
        isoCode: "GQ",
        phoneCode: "240",
        name: "Equatorial Guinea",
        iso3Code: "GNQ",
      ),
      CountryData(
        isoCode: "ER",
        phoneCode: "291",
        name: "Eritrea",
        iso3Code: "ERI",
      ),
      CountryData(
        isoCode: "EE",
        phoneCode: "372",
        name: "Estonia",
        iso3Code: "EST",
      ),
      CountryData(
        isoCode: "ET",
        phoneCode: "251",
        name: "Ethiopia",
        iso3Code: "ETH",
      ),
      CountryData(
        isoCode: "FK",
        phoneCode: "500",
        name: "Falkland Islands (Malvinas)",
        iso3Code: "FLK",
      ),
      CountryData(
        isoCode: "FO",
        phoneCode: "298",
        name: "Faroe Islands",
        iso3Code: "FRO",
      ),
      CountryData(
        isoCode: "FJ",
        phoneCode: "679",
        name: "Fiji",
        iso3Code: "FJI",
      ),
      CountryData(
        isoCode: "FI",
        phoneCode: "358",
        name: "Finland",
        iso3Code: "FIN",
      ),
      CountryData(
        isoCode: "FR",
        phoneCode: "33",
        name: "France",
        iso3Code: "FRA",
      ),
      CountryData(
        isoCode: "GF",
        phoneCode: "594",
        name: "French Guiana",
        iso3Code: "GUF",
      ),
      CountryData(
        isoCode: "PF",
        phoneCode: "689",
        name: "French Polynesia",
        iso3Code: "PYF",
      ),
      CountryData(
        isoCode: "TF",
        phoneCode: "262",
        name: "French Southern Territories",
        iso3Code: "ATF",
      ),
      CountryData(
        isoCode: "GA",
        phoneCode: "241",
        name: "Gabon",
        iso3Code: "GAB",
      ),
      CountryData(
        isoCode: "GM",
        phoneCode: "220",
        name: "Gambia",
        iso3Code: "GMB",
      ),
      CountryData(
        isoCode: "GE",
        phoneCode: "995",
        name: "Georgia",
        iso3Code: "GEO",
      ),
      CountryData(
        isoCode: "DE",
        phoneCode: "49",
        name: "Germany",
        iso3Code: "DEU",
      ),
      CountryData(
        isoCode: "GH",
        phoneCode: "233",
        name: "Ghana",
        iso3Code: "GHA",
      ),
      CountryData(
        isoCode: "GI",
        phoneCode: "350",
        name: "Gibraltar",
        iso3Code: "GIB",
      ),
      CountryData(
        isoCode: "GR",
        phoneCode: "30",
        name: "Greece",
        iso3Code: "GRC",
      ),
      CountryData(
        isoCode: "GL",
        phoneCode: "299",
        name: "Greenland",
        iso3Code: "GRL",
      ),
      CountryData(
        isoCode: "GD",
        phoneCode: "1",
        name: "Grenada",
        iso3Code: "GRD",
      ),
      CountryData(
        isoCode: "GP",
        phoneCode: "590",
        name: "Guadeloupe",
        iso3Code: "GLP",
      ),
      CountryData(
        isoCode: "GU",
        phoneCode: "1",
        name: "Guam",
        iso3Code: "GUM",
      ),
      CountryData(
        isoCode: "GT",
        phoneCode: "502",
        name: "Guatemala",
        iso3Code: "GTM",
      ),
      CountryData(
        isoCode: "GG",
        phoneCode: "441481",
        name: "Guernsey",
        iso3Code: "GGY",
      ),
      CountryData(
        isoCode: "GN",
        phoneCode: "224",
        name: "Guinea",
        iso3Code: "GIN",
      ),
      CountryData(
        isoCode: "GW",
        phoneCode: "245",
        name: "Guinea-Bissau",
        iso3Code: "GNB",
      ),
      CountryData(
        isoCode: "GY",
        phoneCode: "592",
        name: "Guyana",
        iso3Code: "GUY",
      ),
      CountryData(
        isoCode: "HT",
        phoneCode: "509",
        name: "Haiti",
        iso3Code: "HTI",
      ),
      CountryData(
        isoCode: "HM",
        phoneCode: "672",
        name: "Heard Island and McDonald Islands",
        iso3Code: "HMD",
      ),
      CountryData(
        isoCode: "VA",
        phoneCode: "379",
        name: "Holy See (Vatican City State)",
        iso3Code: "VAT",
      ),
      CountryData(
        isoCode: "HN",
        phoneCode: "504",
        name: "Honduras",
        iso3Code: "HND",
      ),
      CountryData(
        isoCode: "HK",
        phoneCode: "852",
        name: "Hong Kong",
        iso3Code: "HKG",
      ),
      CountryData(
        isoCode: "HU",
        phoneCode: "36",
        name: "Hungary",
        iso3Code: "HUN",
      ),
      CountryData(
        isoCode: "IS",
        phoneCode: "354",
        name: "Iceland",
        iso3Code: "ISL",
      ),
      CountryData(
        isoCode: "IN",
        phoneCode: "91",
        name: "India",
        iso3Code: "IND",
      ),
      CountryData(
        isoCode: "ID",
        phoneCode: "62",
        name: "Indonesia",
        iso3Code: "IDN",
      ),
      CountryData(
        isoCode: "IR",
        phoneCode: "98",
        name: "Iran, Islamic Republic of",
        iso3Code: "IRN",
      ),
      CountryData(
        isoCode: "IQ",
        phoneCode: "964",
        name: "Iraq",
        iso3Code: "IRQ",
      ),
      CountryData(
        isoCode: "IE",
        phoneCode: "353",
        name: "Ireland",
        iso3Code: "IRL",
      ),
      CountryData(
        isoCode: "IM",
        phoneCode: "44",
        name: "Isle of Man",
        iso3Code: "IMN",
      ),
      CountryData(
        isoCode: "IL",
        phoneCode: "972",
        name: "Israel",
        iso3Code: "ISR",
      ),
      CountryData(
        isoCode: "IT",
        phoneCode: "39",
        name: "Italy",
        iso3Code: "ITA",
      ),
      CountryData(
        isoCode: "JM",
        phoneCode: "1",
        name: "Jamaica",
        iso3Code: "JAM",
      ),
      CountryData(
        isoCode: "JP",
        phoneCode: "81",
        name: "Japan",
        iso3Code: "JPN",
      ),
      CountryData(
        isoCode: "JE",
        phoneCode: "44",
        name: "Jersey",
        iso3Code: "JEY",
      ),
      CountryData(
        isoCode: "JO",
        phoneCode: "962",
        name: "Jordan",
        iso3Code: "JOR",
      ),
      CountryData(
        isoCode: "KZ",
        phoneCode: "7",
        name: "Kazakhstan",
        iso3Code: "KAZ",
      ),
      CountryData(
        isoCode: "KE",
        phoneCode: "254",
        name: "Kenya",
        iso3Code: "KEN",
      ),
      CountryData(
        isoCode: "KI",
        phoneCode: "686",
        name: "Kiribati",
        iso3Code: "KIR",
      ),
      CountryData(
        isoCode: "KP",
        phoneCode: "850",
        name: "Korea, Democratic People's Republic of",
        iso3Code: "PRK",
      ),
      CountryData(
        isoCode: "KR",
        phoneCode: "82",
        name: "Korea, Republic of",
        iso3Code: "KOR",
      ),
      CountryData(
        isoCode: "XK",
        phoneCode: "383",
        name: "Kosovo",
        iso3Code: "KOS",
      ),
      CountryData(
        isoCode: "KW",
        phoneCode: "965",
        name: "Kuwait",
        iso3Code: "KWT",
      ),
      CountryData(
        isoCode: "KG",
        phoneCode: "996",
        name: "Kyrgyzstan",
        iso3Code: "KGZ",
      ),
      CountryData(
        isoCode: "LA",
        phoneCode: "856",
        name: "Lao People's Democratic Republic",
        iso3Code: "LAO",
      ),
      CountryData(
        isoCode: "LV",
        phoneCode: "371",
        name: "Latvia",
        iso3Code: "LVA",
      ),
      CountryData(
        isoCode: "LB",
        phoneCode: "961",
        name: "Lebanon",
        iso3Code: "LBN",
      ),
      CountryData(
        isoCode: "LS",
        phoneCode: "266",
        name: "Lesotho",
        iso3Code: "LSO",
      ),
      CountryData(
        isoCode: "LR",
        phoneCode: "231",
        name: "Liberia",
        iso3Code: "LBR",
      ),
      CountryData(
        isoCode: "LY",
        phoneCode: "218",
        name: "Libya",
        iso3Code: "LBY",
      ),
      CountryData(
        isoCode: "LI",
        phoneCode: "423",
        name: "Liechtenstein",
        iso3Code: "LIE",
      ),
      CountryData(
        isoCode: "LT",
        phoneCode: "370",
        name: "Lithuania",
        iso3Code: "LTU",
      ),
      CountryData(
        isoCode: "LU",
        phoneCode: "352",
        name: "Luxembourg",
        iso3Code: "LUX",
      ),
      CountryData(
        isoCode: "MO",
        phoneCode: "853",
        name: "Macao",
        iso3Code: "MAC",
      ),
      CountryData(
        isoCode: "MK",
        phoneCode: "389",
        name: "Macedonia, the former Yugoslav Republic of",
        iso3Code: "MKD",
      ),
      CountryData(
        isoCode: "MG",
        phoneCode: "261",
        name: "Madagascar",
        iso3Code: "MDG",
      ),
      CountryData(
        isoCode: "MW",
        phoneCode: "265",
        name: "Malawi",
        iso3Code: "MWI",
      ),
      CountryData(
        isoCode: "MY",
        phoneCode: "60",
        name: "Malaysia",
        iso3Code: "MYS",
      ),
      CountryData(
        isoCode: "MV",
        phoneCode: "960",
        name: "Maldives",
        iso3Code: "MDV",
      ),
      CountryData(
        isoCode: "ML",
        phoneCode: "223",
        name: "Mali",
        iso3Code: "MLI",
      ),
      CountryData(
        isoCode: "MT",
        phoneCode: "356",
        name: "Malta",
        iso3Code: "MLT",
      ),
      CountryData(
        isoCode: "MH",
        phoneCode: "692",
        name: "Marshall Islands",
        iso3Code: "MHL",
      ),
      CountryData(
        isoCode: "MQ",
        phoneCode: "596",
        name: "Martinique",
        iso3Code: "MTQ",
      ),
      CountryData(
        isoCode: "MR",
        phoneCode: "222",
        name: "Mauritania",
        iso3Code: "MRT",
      ),
      CountryData(
        isoCode: "MU",
        phoneCode: "230",
        name: "Mauritius",
        iso3Code: "MUS",
      ),
      CountryData(
        isoCode: "YT",
        phoneCode: "262",
        name: "Mayotte",
        iso3Code: "MYT",
      ),
      CountryData(
        isoCode: "MX",
        phoneCode: "52",
        name: "Mexico",
        iso3Code: "MEX",
      ),
      CountryData(
        isoCode: "FM",
        phoneCode: "691",
        name: "Micronesia, Federated States of",
        iso3Code: "FSM",
      ),
      CountryData(
        isoCode: "MD",
        phoneCode: "373",
        name: "Moldova, Republic of",
        iso3Code: "MDA",
      ),
      CountryData(
        isoCode: "MC",
        phoneCode: "377",
        name: "Monaco",
        iso3Code: "MCO",
      ),
      CountryData(
        isoCode: "MN",
        phoneCode: "976",
        name: "Mongolia",
        iso3Code: "MNG",
      ),
      CountryData(
        isoCode: "ME",
        phoneCode: "382",
        name: "Montenegro",
        iso3Code: "MNE",
      ),
      CountryData(
        isoCode: "MS",
        phoneCode: "1",
        name: "Montserrat",
        iso3Code: "MSR",
      ),
      CountryData(
        isoCode: "MA",
        phoneCode: "212",
        name: "Morocco",
        iso3Code: "MAR",
      ),
      CountryData(
        isoCode: "MZ",
        phoneCode: "258",
        name: "Mozambique",
        iso3Code: "MOZ",
      ),
      CountryData(
        isoCode: "MM",
        phoneCode: "95",
        name: "Myanmar",
        iso3Code: "MMR",
      ),
      CountryData(
        isoCode: "NA",
        phoneCode: "264",
        name: "Namibia",
        iso3Code: "NAM",
      ),
      CountryData(
        isoCode: "NR",
        phoneCode: "674",
        name: "Nauru",
        iso3Code: "NRU",
      ),
      CountryData(
        isoCode: "NP",
        phoneCode: "977",
        name: "Nepal",
        iso3Code: "NPL",
      ),
      CountryData(
        isoCode: "NL",
        phoneCode: "31",
        name: "Netherlands",
        iso3Code: "NLD",
      ),
      CountryData(
        isoCode: "AN",
        phoneCode: "599",
        name: "Netherlands Antilles",
        iso3Code: "AN",
      ),
      CountryData(
        isoCode: "NC",
        phoneCode: "687",
        name: "New Caledonia",
        iso3Code: "NCL",
      ),
      CountryData(
        isoCode: "NZ",
        phoneCode: "64",
        name: "New Zealand",
        iso3Code: "NZL",
      ),
      CountryData(
        isoCode: "NI",
        phoneCode: "505",
        name: "Nicaragua",
        iso3Code: "NIC",
      ),
      CountryData(
        isoCode: "NE",
        phoneCode: "227",
        name: "Niger",
        iso3Code: "NER",
      ),
      CountryData(
        isoCode: "NG",
        phoneCode: "234",
        name: "Nigeria",
        iso3Code: "NGA",
      ),
      CountryData(
        isoCode: "NU",
        phoneCode: "683",
        name: "Niue",
        iso3Code: "NIU",
      ),
      CountryData(
        isoCode: "NF",
        phoneCode: "672",
        name: "Norfolk Island",
        iso3Code: "NFK",
      ),
      CountryData(
        isoCode: "GB-NIR",
        phoneCode: "44",
        name: "Northern Ireland",
        iso3Code: "GBR",
      ),
      CountryData(
        isoCode: "MP",
        phoneCode: "1",
        name: "Northern Mariana Islands",
        iso3Code: "MNP",
      ),
      CountryData(
        isoCode: "NO",
        phoneCode: "47",
        name: "Norway",
        iso3Code: "NOR",
      ),
      CountryData(
        isoCode: "OM",
        phoneCode: "968",
        name: "Oman",
        iso3Code: "OMN",
      ),
      CountryData(
        isoCode: "PK",
        phoneCode: "92",
        name: "Pakistan",
        iso3Code: "PAK",
      ),
      CountryData(
        isoCode: "PW",
        phoneCode: "680",
        name: "Palau",
        iso3Code: "PLW",
      ),
      CountryData(
        isoCode: "PS",
        phoneCode: "970",
        name: "Palestine",
        iso3Code: "PSE",
      ),
      CountryData(
        isoCode: "PA",
        phoneCode: "507",
        name: "Panama",
        iso3Code: "PAN",
      ),
      CountryData(
        isoCode: "PG",
        phoneCode: "675",
        name: "Papua New Guinea",
        iso3Code: "PNG",
      ),
      CountryData(
        isoCode: "PY",
        phoneCode: "595",
        name: "Paraguay",
        iso3Code: "PRY",
      ),
      CountryData(
        isoCode: "PE",
        phoneCode: "51",
        name: "Peru",
        iso3Code: "PER",
      ),
      CountryData(
        isoCode: "PH",
        phoneCode: "63",
        name: "Philippines",
        iso3Code: "PHL",
      ),
      CountryData(
        isoCode: "PN",
        phoneCode: "64",
        name: "Pitcairn",
        iso3Code: "PCN",
      ),
      CountryData(
        isoCode: "PL",
        phoneCode: "48",
        name: "Poland",
        iso3Code: "POL",
      ),
      CountryData(
        isoCode: "PT",
        phoneCode: "351",
        name: "Portugal",
        iso3Code: "PRT",
      ),
      CountryData(
        isoCode: "PR",
        phoneCode: "1",
        name: "Puerto Rico",
        iso3Code: "PRI",
      ),
      CountryData(
        isoCode: "QA",
        phoneCode: "974",
        name: "Qatar",
        iso3Code: "QAT",
      ),
      CountryData(
        isoCode: "RO",
        phoneCode: "40",
        name: "Romania",
        iso3Code: "ROU",
      ),
      CountryData(
        isoCode: "RU",
        phoneCode: "7",
        name: "Russian Federation",
        iso3Code: "RUS",
      ),
      CountryData(
        isoCode: "RW",
        phoneCode: "250",
        name: "Rwanda",
        iso3Code: "RWA",
      ),
      CountryData(
        isoCode: "RE",
        phoneCode: "262",
        name: "Réunion",
        iso3Code: "REU",
      ),
      CountryData(
        isoCode: "BL",
        phoneCode: "590",
        name: "Saint Barthélemy",
        iso3Code: "BLM",
      ),
      CountryData(
        isoCode: "SH",
        phoneCode: "290",
        name: "Saint Helena, Ascension and Tristan da Cunha",
        iso3Code: "SHN",
      ),
      CountryData(
        isoCode: "KN",
        phoneCode: "1",
        name: "Saint Kitts and Nevis",
        iso3Code: "KNA",
      ),
      CountryData(
        isoCode: "LC",
        phoneCode: "1",
        name: "Saint Lucia",
        iso3Code: "LCA",
      ),
      CountryData(
        isoCode: "MF",
        phoneCode: "590",
        name: "Saint Martin",
        iso3Code: "MAF",
      ),
      CountryData(
        isoCode: "PM",
        phoneCode: "508",
        name: "Saint Pierre and Miquelon",
        iso3Code: "SPM",
      ),
      CountryData(
        isoCode: "VC",
        phoneCode: "1",
        name: "Saint Vincent and the Grenadines",
        iso3Code: "VCT",
      ),
      CountryData(
        isoCode: "WS",
        phoneCode: "685",
        name: "Samoa",
        iso3Code: "WSM",
      ),
      CountryData(
        isoCode: "SM",
        phoneCode: "378",
        name: "San Marino",
        iso3Code: "SMR",
      ),
      CountryData(
        isoCode: "ST",
        phoneCode: "239",
        name: "Sao Tome and Principe",
        iso3Code: "STP",
      ),
      CountryData(
        isoCode: "SA",
        phoneCode: "966",
        name: "Saudi Arabia",
        iso3Code: "SAU",
      ),
      CountryData(
        isoCode: "GB-SCT",
        phoneCode: "44",
        name: "Scotland",
        iso3Code: "GBR",
      ),
      CountryData(
        isoCode: "SN",
        phoneCode: "221",
        name: "Senegal",
        iso3Code: "SEN",
      ),
      CountryData(
        isoCode: "RS",
        phoneCode: "381",
        name: "Serbia",
        iso3Code: "SRB",
      ),
      CountryData(
        isoCode: "SC",
        phoneCode: "248",
        name: "Seychelles",
        iso3Code: "SYC",
      ),
      CountryData(
        isoCode: "SL",
        phoneCode: "232",
        name: "Sierra Leone",
        iso3Code: "SLE",
      ),
      CountryData(
        isoCode: "SG",
        phoneCode: "65",
        name: "Singapore",
        iso3Code: "SGP",
      ),
      CountryData(
        isoCode: "SX",
        phoneCode: "721",
        name: "Sint Maarten (Dutch part)",
        iso3Code: "SXM",
      ),
      CountryData(
        isoCode: "SK",
        phoneCode: "421",
        name: "Slovakia",
        iso3Code: "SVK",
      ),
      CountryData(
        isoCode: "SI",
        phoneCode: "386",
        name: "Slovenia",
        iso3Code: "SVN",
      ),
      CountryData(
        isoCode: "SB",
        phoneCode: "677",
        name: "Solomon Islands",
        iso3Code: "SLB",
      ),
      CountryData(
        isoCode: "SO",
        phoneCode: "252",
        name: "Somalia",
        iso3Code: "SOM",
      ),
      CountryData(
        isoCode: "ZA",
        phoneCode: "27",
        name: "South Africa",
        iso3Code: "ZAF",
      ),
      CountryData(
        isoCode: "GS",
        phoneCode: "500",
        name: "South Georgia and the South Sandwich Islands",
        iso3Code: "SGS",
      ),
      CountryData(
        isoCode: "SS",
        phoneCode: "211",
        name: "South Sudan",
        iso3Code: "SSD",
      ),
      CountryData(
        isoCode: "ES",
        phoneCode: "34",
        name: "Spain",
        iso3Code: "ESP",
      ),
      CountryData(
        isoCode: "LK",
        phoneCode: "94",
        name: "Sri Lanka",
        iso3Code: "LKA",
      ),
      CountryData(
        isoCode: "SD",
        phoneCode: "249",
        name: "Sudan",
        iso3Code: "SDN",
      ),
      CountryData(
        isoCode: "SR",
        phoneCode: "597",
        name: "Suriname",
        iso3Code: "SUR",
      ),
      CountryData(
        isoCode: "SJ",
        phoneCode: "47",
        name: "Svalbard and Jan Mayen Islands",
        iso3Code: "SJM",
      ),
      CountryData(
        isoCode: "SZ",
        phoneCode: "268",
        name: "Swaziland",
        iso3Code: "SWZ",
      ),
      CountryData(
        isoCode: "SE",
        phoneCode: "46",
        name: "Sweden",
        iso3Code: "SWE",
      ),
      CountryData(
        isoCode: "CH",
        phoneCode: "41",
        name: "Switzerland",
        iso3Code: "CHE",
      ),
      CountryData(
        isoCode: "SY",
        phoneCode: "963",
        name: "Syrian Arab Republic",
        iso3Code: "SYR",
      ),
      CountryData(
        isoCode: "TW",
        phoneCode: "886",
        name: "Taiwan",
        iso3Code: "TWN",
      ),
      CountryData(
        isoCode: "TJ",
        phoneCode: "992",
        name: "Tajikistan",
        iso3Code: "TJK",
      ),
      CountryData(
        isoCode: "TZ",
        phoneCode: "255",
        name: "Tanzania, United Republic of",
        iso3Code: "TZA",
      ),
      CountryData(
        isoCode: "TH",
        phoneCode: "66",
        name: "Thailand",
        iso3Code: "THA",
      ),
      CountryData(
        isoCode: "TL",
        phoneCode: "670",
        name: "Timor-Leste",
        iso3Code: "TLS",
      ),
      CountryData(
        isoCode: "TG",
        phoneCode: "228",
        name: "Togo",
        iso3Code: "TGO",
      ),
      CountryData(
        isoCode: "TK",
        phoneCode: "690",
        name: "Tokelau",
        iso3Code: "TKL",
      ),
      CountryData(
        isoCode: "TO",
        phoneCode: "676",
        name: "Tonga",
        iso3Code: "TON",
      ),
      CountryData(
        isoCode: "TT",
        phoneCode: "1",
        name: "Trinidad and Tobago",
        iso3Code: "TTO",
      ),
      CountryData(
        isoCode: "TN",
        phoneCode: "216",
        name: "Tunisia",
        iso3Code: "TUN",
      ),
      CountryData(
        isoCode: "TR",
        phoneCode: "90",
        name: "Turkey",
        iso3Code: "TUR",
      ),
      CountryData(
        isoCode: "TM",
        phoneCode: "993",
        name: "Turkmenistan",
        iso3Code: "TKM",
      ),
      CountryData(
        isoCode: "TC",
        phoneCode: "1",
        name: "Turks and Caicos Islands",
        iso3Code: "TCA",
      ),
      CountryData(
        isoCode: "TV",
        phoneCode: "688",
        name: "Tuvalu",
        iso3Code: "TUV",
      ),
      CountryData(
        isoCode: "UG",
        phoneCode: "256",
        name: "Uganda",
        iso3Code: "UGA",
      ),
      CountryData(
        isoCode: "UA",
        phoneCode: "380",
        name: "Ukraine",
        iso3Code: "UKR",
      ),
      CountryData(
        isoCode: "AE",
        phoneCode: "971",
        name: "United Arab Emirates",
        iso3Code: "ARE",
      ),
      CountryData(
        isoCode: "GB",
        phoneCode: "44",
        name: "United Kingdom",
        iso3Code: "GBR",
      ),
      CountryData(
        isoCode: "US",
        phoneCode: "1",
        name: "United States",
        iso3Code: "USA",
      ),
      CountryData(
        isoCode: "UY",
        phoneCode: "598",
        name: "Uruguay",
        iso3Code: "URY",
      ),
      CountryData(
        isoCode: "UM",
        phoneCode: "1",
        name: "US Minor Outlying Islands",
        iso3Code: "UMI",
      ),
      CountryData(
        isoCode: "UZ",
        phoneCode: "998",
        name: "Uzbekistan",
        iso3Code: "UZB",
      ),
      CountryData(
        isoCode: "VU",
        phoneCode: "678",
        name: "Vanuatu",
        iso3Code: "VUT",
      ),
      CountryData(
        isoCode: "VE",
        phoneCode: "58",
        name: "Venezuela, Bolivarian Republic of",
        iso3Code: "VEN",
      ),
      CountryData(
        isoCode: "VN",
        phoneCode: "84",
        name: "Vietnam",
        iso3Code: "VNM",
      ),
      CountryData(
        isoCode: "VG",
        phoneCode: "1",
        name: "Virgin Islands, British",
        iso3Code: "VGB",
      ),
      CountryData(
        isoCode: "VI",
        phoneCode: "1",
        name: "Virgin Islands, U.S.",
        iso3Code: "VIR",
      ),
      CountryData(
        isoCode: "GB-WLS",
        phoneCode: "44",
        name: "Wales",
        iso3Code: "GBR",
      ),
      CountryData(
        isoCode: "WF",
        phoneCode: "681",
        name: "Wallis and Futuna Islands",
        iso3Code: "WLF",
      ),
      CountryData(
        isoCode: "EH",
        phoneCode: "212",
        name: "Western Sahara",
        iso3Code: "ESH",
      ),
      CountryData(
        isoCode: "YE",
        phoneCode: "967",
        name: "Yemen",
        iso3Code: "YEM",
      ),
      CountryData(
        isoCode: "ZM",
        phoneCode: "260",
        name: "Zambia",
        iso3Code: "ZMB",
      ),
      CountryData(
        isoCode: "ZW",
        phoneCode: "263",
        name: "Zimbabwe",
        iso3Code: "ZWE",
      ),
      CountryData(
        isoCode: "AX",
        phoneCode: "358",
        name: "Åland Islands",
        iso3Code: "ALA",
      ),
    ];

    rawData.sort((a, b) {
      return a.name.compareTo(b.name);
    });

    return rawData;
  }
}
