import '../../data/CurrencyData.dart';

class CurrencyCollection {
  static List<CurrencyData> getCurrencies() {
    List<CurrencyData> rawData = [
      CurrencyData(
        code: "USD",
        name: "United States Dollar",
        symbol: "\$",
        flag: "USD",
        decimalDigits: 2,
        number: 840,
        namePlural: "US dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "EUR",
        name: "Euro",
        symbol: "€",
        flag: "EUR",
        decimalDigits: 2,
        number: 978,
        namePlural: "Euros",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "JPY",
        name: "Japanese Yen",
        symbol: "¥",
        flag: "JPY",
        decimalDigits: 0,
        number: 392,
        namePlural: "Japanese yen",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "GBP",
        name: "British Pound",
        symbol: "£",
        flag: "GBP",
        decimalDigits: 2,
        number: 826,
        namePlural: "British pounds sterling",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "AUD",
        name: "Australian Dollar",
        symbol: "\$",
        flag: "AUD",
        decimalDigits: 2,
        number: 36,
        namePlural: "Australian dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "CAD",
        name: "Canadian Dollar",
        symbol: "\$",
        flag: "CAD",
        decimalDigits: 2,
        number: 124,
        namePlural: "Canadian dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "CHF",
        name: "Switzerland Franc",
        symbol: "CHF",
        flag: "CHF",
        decimalDigits: 2,
        number: 756,
        namePlural: "Swiss francs",
        thousandsSeparator: "'",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "CNY",
        name: "China Yuan Renminbi",
        symbol: "¥",
        flag: "CNY",
        decimalDigits: 2,
        number: 156,
        namePlural: "Chinese yuan",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "HKD",
        name: "Hong Kong Dollar",
        symbol: "\$",
        flag: "HKD",
        decimalDigits: 2,
        number: 344,
        namePlural: "Hong Kong dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "NZD",
        name: "New Zealand Dollar",
        symbol: "\$",
        flag: "NZD",
        decimalDigits: 2,
        number: 554,
        namePlural: "New Zealand dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "SEK",
        name: "Sweden Krona",
        symbol: "kr",
        flag: "SEK",
        decimalDigits: 2,
        number: 752,
        namePlural: "Swedish kronor",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "KRW",
        name: "South Korea Won",
        symbol: "₩",
        flag: "KRW",
        decimalDigits: 0,
        number: 410,
        namePlural: "South Korean won",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "SGD",
        name: "Singapore Dollar",
        symbol: "\$",
        flag: "SGD",
        decimalDigits: 2,
        number: 702,
        namePlural: "Singapore dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "NOK",
        name: "Norway Krone",
        symbol: "kr",
        flag: "NOK",
        decimalDigits: 2,
        number: 578,
        namePlural: "Norwegian kroner",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "MXN",
        name: "Mexico Peso",
        symbol: "\$",
        flag: "MXN",
        decimalDigits: 2,
        number: 484,
        namePlural: "Mexican pesos",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "INR",
        name: "Indian Rupee",
        symbol: "₹",
        flag: "INR",
        decimalDigits: 2,
        number: 356,
        namePlural: "Indian rupees",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "RUB",
        name: "Russia Ruble",
        symbol: "₽",
        flag: "RUB",
        decimalDigits: 2,
        number: 643,
        namePlural: "Russian rubles",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "ZAR",
        name: "South Africa Rand",
        symbol: "R",
        flag: "ZAR",
        decimalDigits: 2,
        number: 710,
        namePlural: "South African rand",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "TRY",
        name: "Turkish Lira",
        symbol: "₺",
        flag: "TRY",
        decimalDigits: 2,
        number: 949,
        namePlural: "Turkish Lira",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BRL",
        name: "Brazilian Real",
        symbol: "R\$",
        flag: "BRL",
        decimalDigits: 2,
        number: 986,
        namePlural: "Brazilian Reais",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "TWD",
        name: "Taiwan New Dollar",
        symbol: "NT\$",
        flag: "TWD",
        decimalDigits: 2,
        number: 901,
        namePlural: "New Taiwan dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "DKK",
        name: "Denmark Krone",
        symbol: "kr",
        flag: "DKK",
        decimalDigits: 2,
        number: 208,
        namePlural: "Danish kroner",
        thousandsSeparator: "",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "PLN",
        name: "Poland Zloty",
        symbol: "zł",
        flag: "PLN",
        decimalDigits: 2,
        number: 985,
        namePlural: "Polish zlotys",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "THB",
        name: "Thailand Baht",
        symbol: "฿",
        flag: "THB",
        decimalDigits: 2,
        number: 764,
        namePlural: "Thai baht",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "IDR",
        name: "Indonesia Rupiah",
        symbol: "Rp",
        flag: "IDR",
        decimalDigits: 0,
        number: 360,
        namePlural: "Indonesian rupiahs",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "HUF",
        name: "Hungary Forint",
        symbol: "Ft",
        flag: "HUF",
        decimalDigits: 0,
        number: 348,
        namePlural: "Hungarian forints",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "CZK",
        name: "Czech Koruna",
        symbol: "Kč",
        flag: "CZK",
        decimalDigits: 2,
        number: 203,
        namePlural: "Czech Republic korunas",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "ILS",
        name: "Israel Shekel",
        symbol: "₪",
        flag: "ILS",
        decimalDigits: 2,
        number: 376,
        namePlural: "Israeli new sheqels",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "CLP",
        name: "Chile Peso",
        symbol: "\$",
        flag: "CLP",
        decimalDigits: 0,
        number: 152,
        namePlural: "Chilean pesos",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "PHP",
        name: "Philippines Peso",
        symbol: "₱",
        flag: "PHP",
        decimalDigits: 2,
        number: 608,
        namePlural: "Philippine pesos",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "AED",
        name: "Emirati Dirham",
        symbol: "د.إ",
        flag: "AED",
        decimalDigits: 2,
        number: 784,
        namePlural: "UAE dirhams",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "COP",
        name: "Colombia Peso",
        symbol: "\$",
        flag: "COP",
        decimalDigits: 0,
        number: 170,
        namePlural: "Colombian pesos",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "SAR",
        name: "Saudi Arabia Riyal",
        symbol: "﷼",
        flag: "SAR",
        decimalDigits: 2,
        number: 682,
        namePlural: "Saudi riyals",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "MYR",
        name: "Malaysia Ringgit",
        symbol: "RM",
        flag: "MYR",
        decimalDigits: 2,
        number: 458,
        namePlural: "Malaysian ringgits",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "RON",
        name: "Romania Leu",
        symbol: "L",
        flag: "RON",
        decimalDigits: 2,
        number: 946,
        namePlural: "Romanian lei",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "AFN",
        name: "Afghanistan Afghani",
        symbol: "؋",
        flag: "AFN",
        decimalDigits: 0,
        number: 971,
        namePlural: "Afghan Afghanis",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "ALL",
        name: "Albanian Lek",
        symbol: "Lek",
        flag: "ALB",
        decimalDigits: 0,
        number: 8,
        namePlural: "Albanian lekë",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "DZD",
        name: "Algerian dinar",
        symbol: "دج",
        flag: "DZ",
        decimalDigits: 2,
        number: 12,
        namePlural: "Algerian dinars",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "ARS",
        name: "Argentine Peso",
        symbol: "\$",
        flag: "ARS",
        decimalDigits: 2,
        number: 32,
        namePlural: "Argentine pesos",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "AMD",
        name: "Armenian Dram",
        symbol: "֏",
        flag: "AM",
        decimalDigits: 0,
        number: 51,
        namePlural: "Armenian drams",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "AZN",
        name: "Azerbaijani Manat",
        symbol: "₼",
        flag: "AZE",
        decimalDigits: 2,
        number: 100,
        namePlural: "Azerbaijani manats",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "BHD",
        name: "Bahraini Dinar",
        symbol: "BD",
        flag: "BHD",
        decimalDigits: 3,
        number: 48,
        namePlural: "Bahraini dinars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BDT",
        name: "Bangladeshi Taka",
        symbol: "৳",
        flag: "BDT",
        decimalDigits: 2,
        number: 50,
        namePlural: "Bangladeshi takas",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "BBD",
        name: "Barbados Dollar",
        symbol: "\$",
        flag: "BBD",
        decimalDigits: 2,
        number: 52,
        namePlural: "Barbados dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BYN",
        name: "Belarussian Ruble",
        symbol: "Br",
        flag: "BY",
        decimalDigits: 2,
        number: 933,
        namePlural: "Belarusian rubles",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BZD",
        name: "Belize Dollar",
        symbol: "BZ\$",
        flag: "BZD",
        decimalDigits: 2,
        number: 84,
        namePlural: "Belize dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BMD",
        name: "Bermuda Dollar",
        symbol: "\$",
        flag: "BMD",
        decimalDigits: 2,
        number: 60,
        namePlural: "Bermuda dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BTN",
        name: "Bhutanese Ngultrum",
        symbol: "Nu.",
        flag: "BTN",
        decimalDigits: 2,
        number: 64,
        namePlural: "Bhutanese ngultrums",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BOB",
        name: "Bolivia Bolíviano",
        symbol: "\$b",
        flag: "BOB",
        decimalDigits: 2,
        number: 68,
        namePlural: "Bolivian bolivianos",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BAM",
        name: "Bosnia and Herzegovina convertible mark",
        symbol: "KM",
        flag: "BA",
        decimalDigits: 2,
        number: 977,
        namePlural: "Bosnia and Herzegovina convertible marks",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "BWP",
        name: "Botswanan Pula",
        symbol: "P",
        flag: "BW",
        decimalDigits: 2,
        number: 72,
        namePlural: "Botswanan pulas",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BND",
        name: "Brunei Darussalam Dollar",
        symbol: "\$",
        flag: "BND",
        decimalDigits: 2,
        number: 96,
        namePlural: "Brunei dollars",
        thousandsSeparator: ".",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "BGN",
        name: "Bulgarian Lev",
        symbol: "лв",
        flag: "BGN",
        decimalDigits: 2,
        number: 975,
        namePlural: "Bulgarian leva",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "BIF",
        name: "Burundian Franc",
        symbol: "FBu",
        flag: "BI",
        decimalDigits: 2,
        number: 108,
        namePlural: "Burundian Franc",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "KHR",
        name: "Cambodian riel",
        symbol: "៛",
        flag: "KHM",
        decimalDigits: 2,
        number: 116,
        namePlural: "Cambodian riels",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "KYD",
        name: "Cayman Islands Dollar",
        symbol: "\$",
        flag: "KYD",
        decimalDigits: 2,
        number: 136,
        namePlural: "Cayman islands dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "XAF",
        name: "Central African CFA franc",
        symbol: "FCFA",
        flag: null,
        decimalDigits: 2,
        number: 950,
        namePlural: "Central African CFA francs",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "XOF",
        name: "UEMOA CFA franc",
        symbol: "FCFA",
        flag: "XOF",
        decimalDigits: 2,
        number: 960,
        namePlural: "UEMOA CFA francs",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "CDF",
        name: "Congolese franc",
        symbol: "FC",
        flag: "CD",
        decimalDigits: 2,
        number: 976,
        namePlural: "Congolese francs",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "CRC",
        name: "Costa Rica Colon",
        symbol: "₡",
        flag: "CRC",
        decimalDigits: 0,
        number: 188,
        namePlural: "Costa Rican colóns",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "DOP",
        name: "Dominican Republic Peso",
        symbol: "RD\$",
        flag: "DOP",
        decimalDigits: 2,
        number: 214,
        namePlural: "Dominican pesos",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "EGP",
        name: "Egypt Pound",
        symbol: "£",
        flag: "EGP",
        decimalDigits: 2,
        number: 818,
        namePlural: "Egyptian pounds",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "ETB",
        name: "Ethiopian Birr",
        symbol: "Br",
        flag: "ETB",
        decimalDigits: 2,
        number: 230,
        namePlural: "Ethiopian birrs",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "GMD",
        name: "Gambian dalasi",
        symbol: "D",
        flag: "GMD",
        decimalDigits: 2,
        number: 270,
        namePlural: "Gambian dalasis",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "GEL",
        name: "Georgian Lari",
        symbol: "₾",
        flag: "GEL",
        decimalDigits: 2,
        number: 981,
        namePlural: "Georgian laris",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "GHS",
        name: "Ghana Cedi",
        symbol: "₵",
        flag: "GHS",
        decimalDigits: 2,
        number: 936,
        namePlural: "Ghanaian cedis",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "GTQ",
        name: "Guatemalan quetzal",
        symbol: "Q",
        flag: "GT",
        decimalDigits: 2,
        number: 320,
        namePlural: "Guatemalan quetzales",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "GYD",
        name: "Guyana Dollar",
        symbol: "\$",
        flag: "GYD",
        decimalDigits: 2,
        number: 328,
        namePlural: "Guyana dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "HTG",
        name: "Haitian gourde",
        symbol: "G",
        flag: "HTI",
        decimalDigits: 2,
        number: 332,
        namePlural: "Haitian gourdes",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "ISK",
        name: "Iceland Krona",
        symbol: "kr",
        flag: "ISK",
        decimalDigits: 0,
        number: 352,
        namePlural: "Icelandic krónur",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "IQD",
        name: "Iraqi Dinar",
        symbol: "د.ع",
        flag: "IQD",
        decimalDigits: 3,
        number: 368,
        namePlural: "Iraqi dinars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "JMD",
        name: "Jamaica Dollar",
        symbol: "J\$",
        flag: "JMD",
        decimalDigits: 2,
        number: 388,
        namePlural: "Jamaican dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "JOD",
        name: "Jordanian dinar",
        symbol: "د.أ",
        flag: "JO",
        decimalDigits: 3,
        number: 400,
        namePlural: "Jordanian dinars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "KZT",
        name: "Kazakhstan Tenge",
        symbol: "〒",
        flag: "KZT",
        decimalDigits: 2,
        number: 398,
        namePlural: "Kazakhstani tenges",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "KES",
        name: "Kenyan Shilling",
        symbol: "KSh",
        flag: "KES",
        decimalDigits: 2,
        number: 404,
        namePlural: "Kenyan shillings",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "KWD",
        name: "Kuwaiti Dinar",
        symbol: "د.ك",
        flag: "KWD",
        decimalDigits: 3,
        number: 414,
        namePlural: "Kuwaiti dinars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "KGS",
        name: "Kyrgyzstani som",
        symbol: "с",
        flag: "KG",
        decimalDigits: 2,
        number: 417,
        namePlural: "Kyrgyzstani som",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "LAK",
        name: "Laos Kip",
        symbol: "₭",
        flag: "LAK",
        decimalDigits: 2,
        number: 418,
        namePlural: "Laos Kip",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "LRD",
        name: "Liberia Dollar",
        symbol: "\$",
        flag: "LRD",
        decimalDigits: 2,
        number: 430,
        namePlural: "Liberia dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "MKD",
        name: "Macedonia Denar",
        symbol: "ден",
        flag: "MKD",
        decimalDigits: 2,
        number: 807,
        namePlural: "Macedonian denari",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "MVR",
        name: "Maldivian Rufiyaa",
        symbol: "/-",
        flag: "MV",
        decimalDigits: 2,
        number: 462,
        namePlural: "Maldivian Rufiyaa",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "MWK",
        name: "Malawian Kwacha",
        symbol: "MK",
        flag: "MWK",
        decimalDigits: 2,
        number: 454,
        namePlural: "Malawian kwachas",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "MUR",
        name: "Mauritius Rupee",
        symbol: "₨",
        flag: "MUR",
        decimalDigits: 0,
        number: 480,
        namePlural: "Mauritian rupees",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "MDL",
        name: "Moldovan Leu",
        symbol: "L",
        flag: "MDL",
        decimalDigits: 2,
        number: 498,
        namePlural: "Moldovan lei",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "MNT",
        name: "Mongolia Tughrik",
        symbol: "₮",
        flag: "MNT",
        decimalDigits: 2,
        number: 496,
        namePlural: "Mongolia tugriks",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "MAD",
        name: "Moroccan Dirham",
        symbol: "MAD",
        flag: "MAD",
        decimalDigits: 2,
        number: 504,
        namePlural: "Moroccan dirhams",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "MZN",
        name: "Mozambique Metical",
        symbol: "MT",
        flag: "MZN",
        decimalDigits: 2,
        number: 943,
        namePlural: "Mozambican meticals",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "MMK",
        name: "Myanmar Kyat",
        symbol: "Ks",
        flag: "MM",
        decimalDigits: 2,
        number: 104,
        namePlural: "Myanmar Kyats",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "NAD",
        name: "Namibia Dollar",
        symbol: "\$",
        flag: "NAD",
        decimalDigits: 2,
        number: 516,
        namePlural: "Namibian dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "NPR",
        name: "Nepal Rupee",
        symbol: "₨",
        flag: "NPR",
        decimalDigits: 2,
        number: 524,
        namePlural: "Nepalese rupees",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "NIO",
        name: "Nicaragua Cordoba",
        symbol: "C\$",
        flag: "NIO",
        decimalDigits: 2,
        number: 558,
        namePlural: "Nicaraguan córdobas",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "NGN",
        name: "Nigeria Naira",
        symbol: "₦",
        flag: "NGN",
        decimalDigits: 2,
        number: 566,
        namePlural: "Nigerian nairas",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "OMR",
        name: "Oman Rial",
        symbol: "﷼",
        flag: "OMR",
        decimalDigits: 3,
        number: 512,
        namePlural: "Omani rials",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "PKR",
        name: "Pakistan Rupee",
        symbol: "₨",
        flag: "PKR",
        decimalDigits: 0,
        number: 586,
        namePlural: "Pakistani rupees",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "PGK",
        name: "Papua New Guinean Kina",
        symbol: "K",
        flag: "PGK",
        decimalDigits: 2,
        number: 598,
        namePlural: "Papua New Guinean Kina",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "PYG",
        name: "Paraguay Guarani",
        symbol: "₲",
        flag: "PYG",
        decimalDigits: 0,
        number: 600,
        namePlural: "Paraguayan guaranis",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "PEN",
        name: "Peru Sol",
        symbol: "S/.",
        flag: "PEN",
        decimalDigits: 2,
        number: 604,
        namePlural: "Peruvian nuevos soles",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "QAR",
        name: "Qatar Riyal",
        symbol: "﷼",
        flag: "QAR",
        decimalDigits: 2,
        number: 634,
        namePlural: "Qatari rials",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "RWF",
        name: "Rwandan franc",
        symbol: "FRw",
        flag: "RWA",
        decimalDigits: 0,
        number: 646,
        namePlural: "Rwandan francs",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "RSD",
        name: "Serbia Dinar",
        symbol: "Дин.",
        flag: "RSD",
        decimalDigits: 0,
        number: 941,
        namePlural: "Serbian dinars",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "SCR",
        name: "Seychellois rupee",
        symbol: "₨",
        flag: "SC",
        decimalDigits: 2,
        number: 690,
        namePlural: "Seychelles rupee",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "SOS",
        name: "Somalia Shilling",
        symbol: "S",
        flag: "SOS",
        decimalDigits: 0,
        number: 706,
        namePlural: "Somali shillings",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "LKR",
        name: "Sri Lanka Rupee",
        symbol: "₨",
        flag: "LKR",
        decimalDigits: 2,
        number: 144,
        namePlural: "Sri Lankan rupees",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "SRD",
        name: "Suriname Dollar",
        symbol: "\$",
        flag: "SRD",
        decimalDigits: 2,
        number: 968,
        namePlural: "Suriname Dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "SYP",
        name: "Syrian Lira",
        symbol: "LS",
        flag: "SYP",
        decimalDigits: 2,
        number: 760,
        namePlural: "Syrian lira",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "TZS",
        name: "Tanzanian Shilling",
        symbol: "TSh",
        flag: "TZS",
        decimalDigits: 0,
        number: 834,
        namePlural: "Tanzanian shillings",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "TTD",
        name: "Trinidad and Tobago Dollar",
        symbol: "TT\$",
        flag: "TTD",
        decimalDigits: 2,
        number: 780,
        namePlural: "Trinidad and Tobago dollars",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "TND",
        name: "Tunisian dinar",
        symbol: "د.ت",
        flag: "TN",
        decimalDigits: 3,
        number: 788,
        namePlural: "Tunisian dinars",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "UGX",
        name: "Ugandan Shilling",
        symbol: "USh",
        flag: "UGX",
        decimalDigits: 0,
        number: 800,
        namePlural: "Ugandan shillings",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "UAH",
        name: "Ukraine Hryvnia",
        symbol: "₴",
        flag: "UAH",
        decimalDigits: 2,
        number: 980,
        namePlural: "Ukrainian hryvnias",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "UYU",
        name: "Uruguay Peso",
        symbol: "\$U",
        flag: "UYU",
        decimalDigits: 2,
        number: 858,
        namePlural: "Uruguayan pesos",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "VEF",
        name: "Venezuela Bolívar",
        symbol: "Bs",
        flag: "VEF",
        decimalDigits: 2,
        number: 937,
        namePlural: "Venezuelan bolívars",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "VND",
        name: "Vietnamese Dong",
        symbol: "₫",
        flag: "VND",
        decimalDigits: 0,
        number: 704,
        namePlural: "Vietnamese dong",
        thousandsSeparator: ".",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: false,
      ),
      CurrencyData(
        code: "YER",
        name: "Yemen Rial",
        symbol: "﷼",
        flag: "YER",
        decimalDigits: 0,
        number: 886,
        namePlural: "Yemeni rials",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        spaceBetweenAmountAndSymbol: true,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "ZMW",
        name: "Zambian kwacha",
        symbol: "ZK",
        flag: "ZM",
        decimalDigits: 2,
        number: 967,
        namePlural: "Zambian kwachas",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
      CurrencyData(
        code: "ZWL",
        name: "Zimbabwean Dollar",
        symbol: "\$ZWL",
        flag: "ZW",
        decimalDigits: 2,
        number: 932,
        namePlural: "Zimbabwean dollars",
        thousandsSeparator: " ",
        decimalSeparator: ",",
        spaceBetweenAmountAndSymbol: false,
        symbolOnLeft: true,
      ),
    ];

    return rawData;
  }
}
